# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI110.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 881, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 40, 881, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 70, 881, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 280, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 250, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 220, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_6.setFont(font)
        self.textEdit_6.setTabChangesFocus(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 390, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_7.setFont(font)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 360, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_8.setFont(font)
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 330, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_9.setFont(font)
        self.textEdit_9.setTabChangesFocus(True)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 500, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_10.setFont(font)
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(10, 470, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_11.setFont(font)
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_12.setGeometry(QtCore.QRect(10, 440, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_12.setFont(font)
        self.textEdit_12.setTabChangesFocus(True)
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_13.setGeometry(QtCore.QRect(10, 580, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_13.setFont(font)
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_14 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_14.setGeometry(QtCore.QRect(10, 550, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_14.setFont(font)
        self.textEdit_14.setTabChangesFocus(True)
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_15 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_15.setGeometry(QtCore.QRect(10, 610, 701, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_15.setFont(font)
        self.textEdit_15.setObjectName("textEdit_15")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(900, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(750, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(750, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(750, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(750, 330, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(750, 390, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(750, 360, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(750, 440, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(750, 500, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(750, 470, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(750, 550, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(750, 610, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(750, 580, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(850, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(710, 220, 41, 91))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(710, 330, 41, 91))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(710, 440, 41, 91))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(710, 550, 41, 91))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(850, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.textEdit_16 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_16.setGeometry(QtCore.QRect(10, 100, 881, 111))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.textEdit_16.setFont(font)
        self.textEdit_16.setObjectName("textEdit_16")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(900, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(900, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_23.setObjectName("pushButton_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(self.textEdit.clear)
        self.pushButton_3.clicked.connect(self.textEdit_2.clear)
        self.pushButton_3.clicked.connect(self.textEdit_3.clear)
        self.pushButton_3.clicked.connect(self.textEdit_16.clear)
        self.pushButton_16.clicked.connect(self.textEdit_6.clear)
        self.pushButton_16.clicked.connect(self.textEdit_5.clear)
        self.pushButton_16.clicked.connect(self.textEdit_4.clear)
        self.pushButton_16.clicked.connect(self.textEdit_9.clear)
        self.pushButton_16.clicked.connect(self.textEdit_8.clear)
        self.pushButton_16.clicked.connect(self.textEdit_7.clear)
        self.pushButton_16.clicked.connect(self.textEdit_12.clear)
        self.pushButton_16.clicked.connect(self.textEdit_11.clear)
        self.pushButton_16.clicked.connect(self.textEdit_10.clear)
        self.pushButton_16.clicked.connect(self.textEdit_14.clear)
        self.pushButton_16.clicked.connect(self.textEdit_13.clear)
        self.pushButton_16.clicked.connect(self.textEdit_15.clear)
        self.pushButton_6.clicked.connect(self.textEdit_4.clear)
        self.pushButton_8.clicked.connect(self.textEdit_7.clear)
        self.pushButton_11.clicked.connect(self.textEdit_10.clear)
        self.pushButton_14.clicked.connect(self.textEdit_15.clear)
        self.pushButton_6.clicked.connect(self.textEdit_5.clear)
        self.pushButton_6.clicked.connect(self.textEdit_6.clear)
        self.pushButton_8.clicked.connect(self.textEdit_8.clear)
        self.pushButton_8.clicked.connect(self.textEdit_9.clear)
        self.pushButton_11.clicked.connect(self.textEdit_12.clear)
        self.pushButton_11.clicked.connect(self.textEdit_11.clear)
        self.pushButton_14.clicked.connect(self.textEdit_14.clear)
        self.pushButton_14.clicked.connect(self.textEdit_13.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit, self.textEdit_3)
        MainWindow.setTabOrder(self.textEdit_3, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.textEdit_11)
        MainWindow.setTabOrder(self.textEdit_11, self.textEdit_6)
        MainWindow.setTabOrder(self.textEdit_6, self.textEdit_9)
        MainWindow.setTabOrder(self.textEdit_9, self.textEdit_12)
        MainWindow.setTabOrder(self.textEdit_12, self.textEdit_14)
        MainWindow.setTabOrder(self.textEdit_14, self.textEdit_10)
        MainWindow.setTabOrder(self.textEdit_10, self.textEdit_15)
        MainWindow.setTabOrder(self.textEdit_15, self.textEdit_4)
        MainWindow.setTabOrder(self.textEdit_4, self.textEdit_8)
        MainWindow.setTabOrder(self.textEdit_8, self.textEdit_7)
        MainWindow.setTabOrder(self.textEdit_7, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.textEdit_13)
        MainWindow.setTabOrder(self.textEdit_13, self.textEdit_5)
        MainWindow.setTabOrder(self.textEdit_5, self.textEdit_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "懂球帝批量翻译平台"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "请输入西语新闻标题！"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "请输入西语新闻！"))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "这里为标题的中文翻译结果！"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "这里为西文翻译结果！"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "这里为英文翻译结果！"))
        self.textEdit_6.setPlaceholderText(_translate("MainWindow", "请输入中文评论！"))
        self.textEdit_7.setPlaceholderText(_translate("MainWindow", "这里为西文翻译结果！"))
        self.textEdit_8.setPlaceholderText(_translate("MainWindow", "这里为英文翻译结果！"))
        self.textEdit_9.setPlaceholderText(_translate("MainWindow", "请输入中文评论！"))
        self.textEdit_10.setPlaceholderText(_translate("MainWindow", "这里为西文翻译结果！"))
        self.textEdit_11.setPlaceholderText(_translate("MainWindow", "这里为英文翻译结果！"))
        self.textEdit_12.setPlaceholderText(_translate("MainWindow", "请输入中文评论！"))
        self.textEdit_13.setPlaceholderText(_translate("MainWindow", "这里为英文翻译结果！"))
        self.textEdit_14.setPlaceholderText(_translate("MainWindow", "请输入中文评论！"))
        self.textEdit_15.setPlaceholderText(_translate("MainWindow", "这里为西文翻译结果！"))
        self.pushButton.setText(_translate("MainWindow", "理解翻译"))
        self.pushButton_2.setText(_translate("MainWindow", "全部翻译"))
        self.pushButton_3.setText(_translate("MainWindow", "清除内容"))
        self.pushButton_4.setText(_translate("MainWindow", "中-->西"))
        self.pushButton_5.setText(_translate("MainWindow", "英-->西"))
        self.pushButton_6.setText(_translate("MainWindow", "清   除"))
        self.pushButton_7.setText(_translate("MainWindow", "中-->西"))
        self.pushButton_8.setText(_translate("MainWindow", "清   除"))
        self.pushButton_9.setText(_translate("MainWindow", "英-->西"))
        self.pushButton_10.setText(_translate("MainWindow", "中-->西"))
        self.pushButton_11.setText(_translate("MainWindow", "清   除"))
        self.pushButton_12.setText(_translate("MainWindow", "英-->西"))
        self.pushButton_13.setText(_translate("MainWindow", "中-->西"))
        self.pushButton_14.setText(_translate("MainWindow", "清   除"))
        self.pushButton_15.setText(_translate("MainWindow", "英-->西"))
        self.pushButton_16.setText(_translate("MainWindow", "全部清除"))
        self.pushButton_17.setText(_translate("MainWindow", "复\n"
"制"))
        self.pushButton_18.setText(_translate("MainWindow", "复\n"
"制"))
        self.pushButton_19.setText(_translate("MainWindow", "复\n"
"制"))
        self.pushButton_20.setText(_translate("MainWindow", "复\n"
"制"))
        self.pushButton_21.setText(_translate("MainWindow", "全部导入"))
        self.textEdit_16.setPlaceholderText(_translate("MainWindow", "这里为新闻的中文翻译结果！"))
        self.pushButton_22.setText(_translate("MainWindow", "更换新闻"))
        self.pushButton_23.setText(_translate("MainWindow", "新闻翻译"))

